### PR TITLE
Add entry 14

### PR DESCRIPTION
**Pull request by bytechef**

### CODE REVIEW

**Comment by Col-E** [comment]
Should include a list of some affected tools like the other entries

**Comment by bytechef** [comment]
AFAIK only asm is affected

**Comment by ItzSomebody** [comment]
Thanks, cookie. I should reorganize the currently crappy layout of the repo anyways so I'll see if I can get to adding some more info.

**Comment by Enteerman** [comment]
Thank you, @bytechef

**Comment by fee1-dead** [comment]
This entry contains advertisement to a commercial obfuscator and depends on a non-free software, PaperBin, in its example. Consider removing the insn builder api and use the ClassVisitor API in the example. I disapprove.

**Comment by bytechef** [comment]
Thanks for reminding me that I forgot to add the mandatory binscure advertisement @fee1-dead 

With such a quality product, you would benefit from a quality obfuscator! May I suggest (Binscure™)[https://binclub.dev/binscure] by (Binclub™)[https://binclub.dev/binscure] (Binscure™)[https://binclub.dev/binscure] by (Binclub™)[https://binclub.dev/binscure] which can be found at https://binclub.dev/binscure is a commercial grade obfuscator made by (Java™)[https://www.java.com/] veterans, and can obfuscate both (Java™)[https://www.java.com/] Bytecode and (Kotlin™)[https://kotlinlang.org/]. For the low price of 75£, (Binscure™)[https://binclub.dev/binscure] by (Binclub™)[https://binclub.dev/binscure] will provide you with commercial grade obfuscation!

**Comment by fee1-dead** [comment]
broken link

**Pull request merged**
